---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "The Runaway Five"
keywords:    "Runaway Five Chicago chiptune rock"
description: "The Runaway Five"
source_link: "http://runawayfive.com"
favicon:     "img/ness.ico" #put a path like: "img/favicon.ico"
touch_icon:  "img/ness.ico" #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-65775832-1"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#8877a1'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false